"""Render the errata register as the page a person reads before quoting a phase (A81).

The register (`{APP}_Errata.json`) is the record of every published claim the analysis
later found wrong. It was meant to open Phase 6, and a project that had not reached Phase 6
cited its entries as `E-nn` across every published phase with no document that showed
them: a reader met `see E-07` and had a JSON file to open. This renders the register as `{APP}_Errata.md`,
generated and never edited by hand, so the page and the register cannot disagree.

No date in the output, so the same register gives the same bytes and a change to the page
is a change to the register.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

GENERATED = "<!-- generated-by: ak errata"
REQUIRED = ("id", "original", "corrected", "affected", "source", "cause", "created_at")
SEVERITY_ORDER = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
ERRATA_ID = re.compile(r"^E-(\d+)$")
NONE = "—"


def output_path(output: Path, app: str) -> Path:
    """Beside the phase documents, not the registers: the page is read by a person."""
    return output / f"{app}_Errata.md"


def load_causes(spec: Path) -> dict[str, str]:
    """Cause class -> what it means, from errata-contract.yaml. Empty when unreadable."""
    try:
        import yaml
        data = yaml.safe_load(spec.read_text(encoding="utf-8")) or {}
    except Exception:  # noqa: BLE001 - a legend is not worth failing the page for
        return {}
    classes = data.get("cause_classes") or {}
    return {str(name): " ".join(str((body or {}).get("means") or "").split())
            for name, body in classes.items()}


def _order(entry: dict[str, Any]) -> tuple[int, str]:
    match = ERRATA_ID.match(str(entry.get("id") or ""))
    return (int(match.group(1)) if match else 10**6, str(entry.get("id") or ""))


def _severity(entry: dict[str, Any]) -> tuple[int, tuple[int, str]]:
    return (SEVERITY_ORDER.get(str(entry.get("severity")), 9), _order(entry))


def _list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        return [str(v) for v in value if str(v).strip()]
    return [str(value)] if str(value).strip() else []


def _flat(value: Any) -> str:
    return " ".join(str(value).split())


def _cell(value: Any) -> str:
    return _flat(value).replace("|", "\\|")


def problems(entries: list[dict[str, Any]], causes: dict[str, str]) -> list[str]:
    """What stops an entry being audited (ER-03), in the order the entries are rendered."""
    found: list[str] = []
    seen: set[str] = set()
    for entry in sorted(entries, key=_order):
        ident = str(entry.get("id") or "?")
        if ident in seen:
            found.append(f"{ident} appears more than once")
        seen.add(ident)
        if not ERRATA_ID.match(ident):
            found.append(f"{ident} is not an E-nn identifier")
        missing = [field for field in REQUIRED
                   if not (_list(entry.get(field)) if field == "affected"
                           else str(entry.get(field) or "").strip())]
        if missing:
            found.append(f"{ident} has no {', '.join(missing)}")
        cause = str(entry.get("cause") or "")
        if cause and causes and cause not in causes:
            found.append(f"{ident} names cause {cause}, which errata-contract.yaml does not define")
    return found


def render(entries: list[dict[str, Any]], app: str, causes: dict[str, str] | None = None,
           source: str = "the errata register") -> str:
    causes = causes or {}
    app = app or "App"
    ordered = sorted(entries, key=_order)
    out = [
        f"{GENERATED} -->",
        f"# {app} {NONE} Errata",
        "",
        "Every claim a published phase made and a later reading found wrong. Generated by "
        f"`$ak errata` from {source}; edit the register, not this file.",
        "",
        "**Read this before you quote a phase document.** Each corrected passage is already "
        "fixed in place and marked with its `E-` number. This page is for a reader who saw "
        "an earlier version, or who meets `E-nn` in a document and wants to know what changed.",
        "",
    ]
    if not ordered:
        out += ["No claim published by any phase has been superseded.", ""]
        return "\n".join(out)

    by_severity: dict[str, int] = {}
    for entry in ordered:
        level = str(entry.get("severity") or "unrated")
        by_severity[level] = by_severity.get(level, 0) + 1
    tally = ", ".join(f"{by_severity[k]} {k}" for k in sorted(
        by_severity, key=lambda k: (SEVERITY_ORDER.get(k, 9), k)))
    out += [
        "## At a glance",
        "",
        f"{len(ordered)} correction(s): {tally}. Highest severity first.",
        "",
        "| Errata | Severity | Found in | Cause | Passages affected |",
        "|---|---|---|---|---|",
    ]
    for entry in sorted(ordered, key=_severity):
        ident = str(entry.get("id"))
        phase = entry.get("phase")
        found_in = f"Phase {phase}" if phase not in (None, "") else NONE
        out.append(f"| [{ident}](#{ident.lower()}) | {_cell(entry.get('severity') or NONE)} "
                   f"| {found_in} | {_cell(entry.get('cause') or NONE)} "
                   f"| {len(_list(entry.get('affected')))} |")
    out.append("")

    used = [c for c in sorted({str(e.get("cause") or "") for e in ordered}) if c in causes]
    if used:
        out += ["Causes, from `specifications/errata-contract.yaml`:", ""]
        out += [f"- `{c}` {NONE} {causes[c]}" for c in used]
        out.append("")

    out += ["## Entries", ""]
    for entry in ordered:
        facts = [str(entry.get("severity") or "")]
        if entry.get("phase") not in (None, ""):
            facts.append(f"found in Phase {entry.get('phase')}")
        facts.append(str(entry.get("cause") or ""))
        out += [f"### {entry.get('id')}", "", "*" + " · ".join(f for f in facts if f) + "*", ""]
        out += ["**Was said.** " + _flat(entry.get("original") or NONE), ""]
        out += ["**Is true.** " + _flat(entry.get("corrected") or NONE), ""]
        affected = _list(entry.get("affected"))
        if affected:
            out += ["**Carried by:**", ""] + [f"- {a}" for a in affected] + [""]
        if entry.get("source"):
            out += [f"**Settled by:** `{entry.get('source')}`", ""]
        superseded = _list(entry.get("superseded_evidence_ids"))
        if superseded:
            out += ["**Evidence it supersedes:** " + ", ".join(f"`{s}`" for s in superseded), ""]
        if str(entry.get("note") or "").strip():
            out += ["**Note.** " + _flat(entry.get("note")), ""]
    return "\n".join(out)
